#!/bin/bash
#previous row is special for scrypt
#the others with '#' are comments
echo "The current directory is:"
#use echo to supply comments
pwd
#use of system variables
echo "Home for the current user is: $HOME"
#use of screening?
echo "I have \$1 in my pocket"
#use of variables
grade=5
person="Adam"
echo "$person is a good boy, he is in grade $grade"
#save result of command into variable
mydir=$(pwd)
echo $mydir
#use mathematics
var1=$(( 5 + 5 ))
echo $var1
var2=$(( $var1 * 2 ))
echo $var2
# 'if then elif else fi' works like this
# 'grep' returns 0 if it successes

user=anotherUser
if grep $user $(ls /home)
then
echo "The user $user Exists"
elif [ $var1 -gt 5 ]
then
# -eq -ge -gt -le -lt -ne
# and for strings use = != < > -n -z (length >0 and =0)
# '<' '>' should be screened like this '\>' '\<'
# and there is some problems with quotes
echo "$var1 gt than 5"
else
echo "The user $user doesn’t exist"
fi
#commands are sepparates with 'new line'
#';' are allowed
# after use 'chmod +x ./bashScrypt' to make it executable
# and then you can just use it with './bashScrypt'

#-d fileПроверяет, существует ли файл, и является ли он директорией.
#-e fileПроверяет, существует ли файл.
#-f file Проверяет, существует ли файл, и является ли он файлом.
#-r fileПроверяет, существует ли файл, и доступен ли он для чтения.
#-s file Проверяет, существует ли файл, и не является ли он пустым.
#-w fileПроверяет, существует ли файл, и доступен ли он для записи.
#-x fileПроверяет, существует ли файл, и является ли он исполняемым.
#file1 -nt file2 Проверяет, новее ли file1, чем file2.
#file1 -ot file2Проверяет, старше ли file1, чем file2.
#-O file Проверяет, существует ли файл, и является ли его владельцем текущий пользователь.
#-G fileПроверяет, существует ли файл, и соответствует ли его идентификатор группы идентификатору группы текущего пользователя.
mydir=goProjects
if [ -d $mydir ]
then
echo "The $mydir directory exists"
cd $mydir
ls
else
echo "The $mydir directory does not exist"
fi